export const REQUESTING_CHANGE_PASSWORD = 'REQUESTING_CHANGE_PASSWORD';
export const SUCCESS_CHANGE_PASSWORD = 'SUCCESS_CHANGE_PASSWORD';
export const UNSUCCESS_CHANGE_PASSWORD = 'UNSUCCESS_CHANGE_PASSWORD';
export const ERROR_CHANGE_PASSWORD = 'ERROR_CHANGE_PASSWORD';
