export const LOGIN_REQUESTING = 'LOGIN_REQUESTING';
export const SUCCESS_IN_REGISTER = 'SUCCESS_IN_REGISTER';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGIN_UNSUCCESS = 'LOGIN_UNSUCCESS';
