export const REQUESTING_RESET_PASSWORD = 'REQUESTING_RESET_PASSWORD';
export const SUCCESS_RESET_PASSWORD = 'SUCCESS_RESET_PASSWORD';
export const UNSUCCESS_RESET_PASSWORD = 'UNSUCCESS_RESET_PASSWORD';
export const ERROR_RESET_PASSWORD = 'ERROR_RESET_PASSWORD';
