export const REQUESTING_FORGOT_PASSWORD = 'REQUESTING_FORGOT_PASSWORD';
export const SUCCESS_FORGOT_PASSWORD = 'SUCCESS_FORGOT_PASSWORD';
export const UNSUCCESS_FORGOT_PASSWORD = 'UNSUCCESS_FORGOT_PASSWORD';
export const ERROR_FORGOT_PASSWORD = 'ERROR_FORGOT_PASSWORD';
